name: CI

on:
  push:
  pull_request:

jobs:
  sync-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extra: [cpu, cu128, rocm]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync --extra ${{ matrix.extra }}

      - name: Smoke test torch
        run: uv run python scripts/smoke.py
